### ISSUE TITLE
Integrated with stocktrading.report

### ISSUE THREAD

**Issue by fedosejev** [markalfred/robinhood-to-csv#5]
Hey Mark, I am working on this project: https://github.com/fedosejev/stock-trading-transactions-analysis and I've added support for the CSV format that your app produces.

It would be great if you could test it if you have a Robinhood account - unfortunately, Robinhood is not available here in the UK.

I think your project fits nicely into the workflow of extracting and visualising Robinhood data - maybe we should collaborate?

**Comment by markalfred** [comment]
@fedosejev I'd love to. I've finally gotten around to introducing some test coverage for this, so that should make it easier to keep expectations consistent. The change also exposes some of the internal functionality so you may be able to reuse a bunch of the methods provided here. Your project looks really interesting, I'll poke around a bit soon!

**Comment by markalfred** [comment]
Closing this for now
